# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

[window]

opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

# meliora, ashes_dark, 

[general]
import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

#[font]

#normal.family = "Cascadia Code PL"
#bold.family = "Cascadia Code PL"
#italic.family = "Cascadia Code PL"
#bold_italic.family = "Cascadia Code PL"

#size = 15.0
